name                'symfony_env'
maintainer          'Ilya Pokamestov'
maintainer_email    'dario_swain@yahoo.com'
license             'all_rights'
description         'Installs/Configures symfony_env'
long_description    'Installs/Configures symfony_env'
version             '0.1.0'